### your site title here

title: LIFT ELT
description: Supporting MLLs | Planning from the Ground Up 

# baseurl: "/"    #name of GitHub repository
relative_url: "/"
# url: "/" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /projects/:year/:title/
paginate_path: /projects/page:num/

# # Social media links in footer
# twitter: "#"
# linkedin: "#"
# stackoverflow: "#"
# github: "#"
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
# facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  webinars:
    output: true
    permalink: /webinars/:name/
    order:
      - fall2023webinars.md
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  #- jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
