theme: jekyll-theme-minimal
title: LIFT-ELT
subtitle: Planning from the ground up
name: LIFT ELT
description:  Important information will be here soon!
url: https://www.lift-elt.com
masthead_title: "LIFT-ELT"
show_date: false
read_time: true
words_per_minute: 200
atom_feed:
  hide: true
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: amber.warren@gmail.com
minimal_mistakes_skin: dirt
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#link: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-pdf-embed
  - jekyll-titles-from-headings


  # This is the stuff on the left of the home page
author:
  name   : "LIFT ELT"
  avatar : "/assets/images/LIFTlogo_new.png"
  bio    : "Support for multilingual learners:
  Planning from the ground up."
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/ambernwarren"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/amber-warren"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/ambernwarren"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/amber-warren"
      
defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# category_archive:
#   type: liquid
#   path: /categories/
head_scripts: 
  - https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.8.335/pdf.min.js
  
tag_archive:
  type: liquid
  path: /tags/

theme: jekyll-theme-modernist
