theme: jekyll-theme-minimal
title: LIFT-ELT
subtitle: Helping teachers with language learners
name: Amber Warren, PhD
description:  Important information will be here soon!
url: https://lift-elt.github.io/
masthead_title: "LIFT-ELT Title"
show_date: false
read_time: true
words_per_minute: 200

# navigation is in _data/navigation.html
# logo: /assets/images/logo.png
# see https://github.com/pages-themes/leap-day for info about leap day theme
# remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0 # https://github.com/pages-themes/modernist
# remote_theme: pages-themes/tactile@v0.2.0 # https://github.com/pages-themes/tactile
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: aqua

markdown: kramdown

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: false # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
# collections:
#   pages:
#     output: true
#     permalink: /:path/
defaults:
  - scope:
      path: "/"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-pdf-embed
  
